### ISSUE TITLE
about looping statement

### ISSUE THREAD

**Issue by 40bit23** [vtcbca/basic-programming-40bit23#2]

**Comment by 40bit23** [comment]
what is looping statement

**Comment by 11bit23** [comment]
looping statement means condition is many time reapete whene condition in true

**Comment by 40bit23** [comment]
ok but i have no knowladge about looping statement  can u explain  plzzzz.......

**Comment by 11bit23** [comment]
ok but you have something knowladge about looping statement
 then i explain  to you

**Comment by 40bit23** [comment]
ok bro but i have no knowladge
plzz explain

**Comment by 11bit23** [comment]
ok looping statement is check the condition and make the program in a easy way  to solve

**Comment by 40bit23** [comment]
ok but  how to write condition???????

**Comment by 11bit23** [comment]
are kay aadmi hai re tu

**Comment by 40bit23** [comment]
are yarr kay karu

**Comment by 11bit23** [comment]
accha ruk  i wiil write..

**Comment by 40bit23** [comment]
ok

**Comment by 11bit23** [comment]
like (i=0,1<4,i++);

**Comment by 40bit23** [comment]
ok i will try in my laptop

**Comment by 11bit23** [comment]
ok ok try

**Comment by 40bit23** [comment]
thanks

**Comment by 11bit23** [comment]
no thanks give some feedback

**Comment by 40bit23** [comment]
ok what

**Comment by 11bit23** [comment]
can u  gause

**Comment by 40bit23** [comment]
no

**Comment by 11bit23** [comment]
lapinozz me party 
karte hai

**Comment by 40bit23** [comment]
ha ha bhai

**Comment by 40bit23** [comment]
you are play game like free fire or pubg

**Comment by 11bit23** [comment]
yes free fire

**Comment by 40bit23** [comment]
give your user id of game

**Comment by 11bit23** [comment]
ok
